## Neural network with a Perceptron

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
from sklearn.linear_model import Perceptron

In [5]:
iris = datasets.load_iris()
x= iris.data
y=iris.target

x[0:10, ]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.2, random_state=17)

In [8]:
standardize = StandardScaler()
standardized_x_test = standardize.fit_transform(x_test)
standardized_x_train = standardize.fit_transform(x_train)

In [9]:
standardized_x_test[0:10,]

array([[-0.64325669,  2.16518556, -1.74844564, -1.31220275],
       [ 0.26132303, -0.34275138,  0.28118896,  0.20187735],
       [ 1.31666604, -0.09195769,  0.72517153,  1.30302651],
       [-0.19096683, -0.59354508,  0.02748464, -0.07340994],
       [ 0.5628496 , -0.59354508,  0.4714672 ,  0.61480828],
       [ 0.41208632, -0.09195769,  0.53489328,  0.61480828],
       [-0.64325669, -0.09195769,  0.28118896,  0.20187735],
       [ 2.82429891,  1.91439187,  1.67656274,  1.16538286],
       [-0.4924934 , -1.59671985, -0.16279361, -0.34869723],
       [-0.19096683, -1.34592616,  0.59831937,  0.89009557]])

In [11]:
perceptron = Perceptron(max_iter=50, eta0=.15, tol=1e-3, random_state=15)
perceptron.fit(standardized_x_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [12]:
y_pred = perceptron.predict(standardized_x_test)

In [14]:
print(y_test)

[0 1 2 1 2 2 1 2 1 2 2 0 1 0 2 0 0 2 2 2 2 0 2 1 1 1 1 1 0 1]


In [15]:
print(y_pred)

[0 1 2 1 1 2 0 2 1 2 2 0 1 0 2 0 0 2 2 2 1 0 2 1 0 0 1 1 0 1]


In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.70      1.00      0.82         7
           1       0.80      0.73      0.76        11
           2       1.00      0.83      0.91        12

    accuracy                           0.83        30
   macro avg       0.83      0.85      0.83        30
weighted avg       0.86      0.83      0.84        30

